/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module mux41(a, b, c, d, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  wire y;
  sky130_fd_sc_hd__mux4_1 _0_ (
    .A0(a),
    .A1(b),
    .A2(c),
    .A3(d),
    .S0(sel[0]),
    .S1(sel[1]),
    .X(y)
  );
endmodule
